name: countries_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  #Here by default, useful to show cupertion icons
  cupertino_icons: ^1.0.2
  
  # helps cache images from the network to avoid uncessary network calls
  cached_network_image: ^3.2.2

  #Used to make network calls
  dio: ^4.0.6

  # Implements google fonts api to provide custom fonts
  google_fonts: ^3.0.1

  #An efficient way to for object equality
  equatable: ^2.0.5


  flutter_hooks: ^0.18.5+1

  #Consistent and pixel perfect helper
  flutter_screenutil: ^5.6.0

  #Provides fluent page view indicators
  smooth_page_indicator: ^1.0.0+2

  #used to display a shimmer effect when UI loading
  shimmer: ^2.0.0

  #Provider state management library extension with classes to boost mvvm architecture
  stacked: ^3.0.0
  stacked_hooks: ^0.2.2
  stacked_services: ^0.9.8

  #Logging info to the console
  logger: ^1.1.0

  # package used to incorperate webview in flutter
  webview_flutter: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^3.1.0
  build_runner: ^2.3.2
  stacked_generator: ^0.8.0+1


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
